name: Nightly Builds Update

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update_builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: ReHLDS
        id: update_rehlds
        run: |
          LATEST_RUN_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/ReHLDS/actions/runs?branch=master&status=success&per_page=1" | jq -r '.workflow_runs[0].id')
          ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/ReHLDS/actions/runs/${LATEST_RUN_ID}/artifacts" | jq -r '.artifacts[] | select(.name=="linux32").id')
          REHLDS_COMMIT_SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/ReHLDS/actions/runs/${LATEST_RUN_ID}" | jq -r '.head_sha')
          echo "sha=$REHLDS_COMMIT_SHA" >> $GITHUB_OUTPUT
          curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o linux32.zip "https://api.github.com/repos/rehlds/ReHLDS/actions/artifacts/${ARTIFACT_ID}/zip"
          unzip linux32.zip -d extracted_rehlds_files
          cp -rf extracted_rehlds_files/bin/linux32/* .
          git add $(ls extracted_rehlds_files/bin/linux32 | xargs -I {} echo "{}")
          if ! git diff-index --quiet HEAD; then
            echo "rehlds_changed=true" >> $GITHUB_OUTPUT
          fi
          rm -rf extracted_rehlds_files linux32.zip

      - name: ReGameDLL
        id: update_regamedll
        run: |
          LATEST_RUN_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/ReGameDLL_CS/actions/runs?branch=master&status=success&per_page=1" | jq -r '.workflow_runs[0].id')
          ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/ReGameDLL_CS/actions/runs/${LATEST_RUN_ID}/artifacts" | jq -r '.artifacts[] | select(.name=="linux32").id')
          REGAMEDLL_COMMIT_SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/ReGameDLL_CS/actions/runs/${LATEST_RUN_ID}" | jq -r '.head_sha')
          echo "sha=$REGAMEDLL_COMMIT_SHA" >> $GITHUB_OUTPUT
          curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o linux32.zip "https://api.github.com/repos/rehlds/ReGameDLL_CS/actions/artifacts/${ARTIFACT_ID}/zip"
          mkdir -p extracted_regamedll_files
          unzip linux32.zip -d extracted_regamedll_files
          mkdir -p cstrike/dlls
          cp extracted_regamedll_files/bin/linux32/cstrike/dlls/cs.so cstrike/dlls/
          cp -r extracted_regamedll_files/dist/* cstrike/
          git add cstrike/dlls/cs.so
          git add cstrike/
          if ! git diff-index --quiet HEAD; then
            echo "regamedll_changed=true" >> $GITHUB_OUTPUT
          fi
          rm -rf extracted_regamedll_files linux32.zip

      - name: Metamod-R
        id: update_metamodr
        run: |
          LATEST_RUN_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/Metamod-R/actions/runs?branch=master&status=success&per_page=1" | jq -r '.workflow_runs[0].id')
          ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/Metamod-R/actions/runs/${LATEST_RUN_ID}/artifacts" | jq -r '.artifacts[] | select(.name=="linux32").id')
          METAMODR_COMMIT_SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/Metamod-R/actions/runs/${LATEST_RUN_ID}" | jq -r '.head_sha')
          echo "sha=$METAMODR_COMMIT_SHA" >> $GITHUB_OUTPUT
          curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o linux32.zip "https://api.github.com/repos/rehlds/Metamod-R/actions/artifacts/${ARTIFACT_ID}/zip"
          mkdir -p extracted_metamodr_files
          unzip linux32.zip -d extracted_metamodr_files
          TARGET_DIR="cstrike/addons/metamod/dlls"
          mkdir -p "$TARGET_DIR"
          cp extracted_metamodr_files/addons/metamod/metamod_i386.so "$TARGET_DIR"
          git add cstrike/addons/metamod/dlls/metamod_i386.so
          if ! git diff-index --quiet HEAD; then
            echo "metamodr_changed=true" >> $GITHUB_OUTPUT
          fi
          rm -rf extracted_metamodr_files linux32.zip

      - name: ReAPI
        id: update_reapi
        run: |
          LATEST_RUN_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/ReAPI/actions/runs?branch=master&status=success&per_page=1" | jq -r '.workflow_runs[0].id')
          ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/ReAPI/actions/runs/${LATEST_RUN_ID}/artifacts" | jq -r '.artifacts[] | select(.name=="linux32").id')
          REAPI_COMMIT_SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/rehlds/ReAPI/actions/runs/${LATEST_RUN_ID}" | jq -r '.head_sha')
          echo "sha=$REAPI_COMMIT_SHA" >> $GITHUB_OUTPUT
          curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o linux32.zip "https://api.github.com/repos/rehlds/ReAPI/actions/artifacts/${ARTIFACT_ID}/zip"
          mkdir -p extracted_reapi_files
          unzip linux32.zip -d extracted_reapi_files
          TARGET_DIR="cstrike/addons/amxmodx/modules"
          mkdir -p "$TARGET_DIR"
          cp extracted_reapi_files/addons/amxmodx/modules/reapi_amxx_i386.so "$TARGET_DIR"
          git add cstrike/addons/amxmodx/modules/reapi_amxx_i386.so
          if ! git diff-index --quiet HEAD; then
            echo "reapi_changed=true" >> $GITHUB_OUTPUT
          fi
          rm -rf extracted_reapi_files linux32.zip

      - name: Update main repository with new builds
        run: |
          GIT_MESSAGE="Nightly builds update"
          if [[ "${{ steps.update_rehlds.outputs.rehlds_changed }}" == 'true' ]]; then
            GIT_MESSAGE="$GIT_MESSAGE\n- ReHLDS updated to commit SHA: ${{ steps.update_rehlds.outputs.sha }}"
          fi
          if [[ "${{ steps.update_regamedll.outputs.regamedll_changed }}" == 'true' ]]; then
            GIT_MESSAGE="$GIT_MESSAGE\n- ReGameDLL updated to commit SHA: ${{ steps.update_regamedll.outputs.sha }}"
          fi
          if [[ "${{ steps.update_metamodr.outputs.metamodr_changed }}" == 'true' ]]; then
            GIT_MESSAGE="$GIT_MESSAGE\n- Metamod-R updated to commit SHA: ${{ steps.update_metamodr.outputs.sha }}"
          fi
          if [[ "${{ steps.update_reapi.outputs.reapi_changed }}" == 'true' ]]; then
            GIT_MESSAGE="$GIT_MESSAGE\n- ReAPI updated to commit SHA: ${{ steps.update_reapi.outputs.sha }}"
          fi
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions Bot"
          git commit -m "$(echo -e "$GIT_MESSAGE")"
          git push
